default: &default
  adapter: mysql2
  encoding: utf8
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  username: "<%= ENV.fetch('DATABASE_USERNAME') { 'root' } %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD') { '' } %>"
  host:     "<%= ENV.fetch('DATABASE_HOST') { '127.0.0.1' } %>"

development:
  <<: *default
  database: "<%= ENV.fetch('DATABASE_NAME') { 'on_development' } %>"

staging:
  <<: *default
  database: "<%= ENV.fetch('DATABASE_NAME') { 'on_staging' } %>"

production:
  <<: *default
  database: "<%= ENV.fetch('DATABASE_NAME') { 'on_production' } %>"

test:
  <<: *default
  username: "<%= ENV.fetch('TEST_DATABASE_USERNAME') { 'root' } %>"
  password: "<%= ENV.fetch('TEST_DATABASE_PASSWORD') { '' } %>"
  host:     "<%= ENV.fetch('TEST_DATABASE_HOST') { '127.0.0.1' } %>"
  database: "<%= ENV.fetch('TEST_DATABASE_NAME') { 'on_test'} %>"
